/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nacho
 */
public class Agregar_Evento extends javax.swing.JFrame {

    Statement st = null;
    ResultSet rs = null;

    Conectar cc= new Conectar();
    Connection cn= cc.conexion();
    
    public Agregar_Evento() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrardatose("");
    }

    void mostrardatose(String valor){
    DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("Código");
    modelo.addColumn("Nombre");    
    modelo.addColumn("Dirección");
    modelo.addColumn("Categoría");
    modelo.addColumn("Contacto");
    modelo.addColumn("Descripción");
    modelo.addColumn("Fecha");
    modelo.addColumn("Latitud");
    modelo.addColumn("Longitud");    
    tb_evento.setModel(modelo);
    String sql="";
    if(valor.equals(""))
    {
        sql="SELECT * FROM evento";
    }
    else{
        sql="SELECT * FROM evento WHERE cod_evento='"+valor+"'";
    }
    
        String []datos = new String [9];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(7);
                String c;
                c = obtenernom_cat(rs.getString(3));
                datos[3]=c;
                datos[4]=rs.getString(5);
                datos[5]=rs.getString(6);
                datos[6]=rs.getString(4);
                datos[7]=rs.getString(8);
                datos[8]=rs.getString(9);
                modelo.addRow(datos);
            }
            tb_evento.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Agregar_Local.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXT_COD_EVENTO = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BTN_SALIR = new javax.swing.JButton();
        BTN_ACEPTAR = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TXT_NOMBRE_E1 = new javax.swing.JTextField();
        TXT_DIRECCION_E1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CB_GENERO1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        CB_CATEGORIA_E1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        TXT_DESCRIPCION_E1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        TXT_CONTACTO_E1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        TXT_FECHA_E = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        TXT_LATITUD_E = new javax.swing.JTextField();
        TXT_LONGITUD_E = new javax.swing.JTextField();
        CB_GENERO2 = new javax.swing.JComboBox<>();
        CB_GENERO3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_evento = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        TXT_COD_EVENTO.setText("jLabel20");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(580, 600));
        setMinimumSize(new java.awt.Dimension(580, 600));
        setPreferredSize(new java.awt.Dimension(580, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Detalle de Eventos");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(202, 11, 146, 22);

        BTN_SALIR.setText("Atrás");
        BTN_SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_SALIR);
        BTN_SALIR.setBounds(447, 512, 67, 23);

        BTN_ACEPTAR.setText("Agregar");
        BTN_ACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ACEPTARActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_ACEPTAR);
        BTN_ACEPTAR.setBounds(47, 512, 71, 23);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        jLabel10.setText("Nombre");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(40, 10, 60, 14);
        jPanel2.add(TXT_NOMBRE_E1);
        TXT_NOMBRE_E1.setBounds(123, 3, 361, 30);
        jPanel2.add(TXT_DIRECCION_E1);
        TXT_DIRECCION_E1.setBounds(123, 39, 361, 30);

        jLabel11.setText("Dirección");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(36, 42, 70, 14);

        CB_GENERO1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        jPanel2.add(CB_GENERO1);
        CB_GENERO1.setBounds(120, 110, 130, 20);

        jLabel12.setText("Género");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(36, 99, 60, 14);

        CB_CATEGORIA_E1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MUSICA", "CINEMATOGRAFICO" }));
        CB_CATEGORIA_E1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CB_CATEGORIA_E1ItemStateChanged(evt);
            }
        });
        jPanel2.add(CB_CATEGORIA_E1);
        CB_CATEGORIA_E1.setBounds(120, 80, 120, 20);

        jLabel13.setText("Categorìa");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(36, 68, 70, 14);
        jPanel2.add(TXT_DESCRIPCION_E1);
        TXT_DESCRIPCION_E1.setBounds(123, 147, 361, 40);

        jLabel14.setText("Descripción");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(30, 140, 80, 40);
        jPanel2.add(TXT_CONTACTO_E1);
        TXT_CONTACTO_E1.setBounds(123, 205, 361, 30);

        jLabel15.setText("Contacto");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(36, 203, 80, 20);
        jPanel2.add(TXT_FECHA_E);
        TXT_FECHA_E.setBounds(123, 243, 188, 30);

        jLabel17.setText("Fecha");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(36, 246, 70, 14);

        jLabel18.setText("Latitud");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(36, 284, 70, 14);

        jLabel19.setText("Longitud");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(270, 284, 60, 14);
        jPanel2.add(TXT_LATITUD_E);
        TXT_LATITUD_E.setBounds(123, 281, 137, 30);
        jPanel2.add(TXT_LONGITUD_E);
        TXT_LONGITUD_E.setBounds(320, 281, 164, 30);

        jPanel2.add(CB_GENERO2);
        CB_GENERO2.setBounds(250, 110, 120, 20);

        jPanel2.add(CB_GENERO3);
        CB_GENERO3.setBounds(370, 110, 118, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 60, 550, 320);

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(166, 512, 79, 23);

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(302, 512, 77, 23);

        tb_evento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_evento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_eventoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_evento);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 393, 551, 101);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/Fondo-celeste-copia-1024x1024.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 610, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SALIRActionPerformed
        Inicio v2 = new Inicio();
        dispose();
        v2.setVisible(true);
    }//GEN-LAST:event_BTN_SALIRActionPerformed

    private void BTN_ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ACEPTARActionPerformed
        String nombre = TXT_NOMBRE_E1.getText();  
        String direccion = TXT_DIRECCION_E1.getText();
        String fecha = TXT_FECHA_E.getText();
        validar_evento(nombre,direccion,fecha); 
        mostrardatose("");
        Limpiar();
 
 
    }//GEN-LAST:event_BTN_ACEPTARActionPerformed

    String validar_evento(String valor , String valor2, String valor3){
        String vali = "";
        try {
            String csql = "SELECT * FROM evento WHERE nom_even='"+valor+"' and direccion_e = '"+valor2+"' and fecha = '"+valor3+"'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(csql);
            while(rs.next()){
                vali=rs.getString(1); 
            } 
        }
        catch(Exception e){
            System.out.println("Falló la carga del combobox \n"+e);              
        }
        if (vali.equals("")){
       try {
            if (TXT_NOMBRE_E1.getText().equals("") || TXT_DIRECCION_E1.getText().equals("") || TXT_LATITUD_E.getText().equals("")|| TXT_LONGITUD_E.getText().equals("")|| TXT_FECHA_E.getText().equals("")){
                JOptionPane.showMessageDialog(null, "No puede dejar campos en blanco.");
            }else{
        PreparedStatement pst = cn.prepareStatement("INSERT INTO evento(nom_even,cod_cat,fecha,contacto_e,descripcion_e,direccion_e,latitud_e,longitud_e) VALUES (?,?,?,?,?,?,?,?)");
        pst.setString(1, TXT_NOMBRE_E1.getText());
        pst.setString(6, TXT_DIRECCION_E1.getText());
        String a;
        a = obtenercod_cat(CB_CATEGORIA_E1.getSelectedItem().toString());
        pst.setString(2,a);
        pst.setString(3,TXT_FECHA_E.getText());
        pst.setString(4, TXT_CONTACTO_E1.getText());
        pst.setString(5, TXT_DESCRIPCION_E1.getText());        
        pst.setString(7,TXT_LATITUD_E.getText());
        pst.setString(8, TXT_LONGITUD_E.getText());
        pst.executeUpdate();

        
        JOptionPane.showMessageDialog(null, "Evento Agregado");
        String sql = "Select cod_even from evento where nom_even = '"+ TXT_NOMBRE_E1.getText() +"'";
        Statement st = cn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        rs.next();
        String ex = rs.getString(1);
        PreparedStatement pstg = cn.prepareStatement("INSERT INTO even_gen(cod_even,cod_gen) VALUES (?,?) ");
        pstg.setString(1, ex);
        String g;
        g = obtenercod_gen(CB_GENERO1.getSelectedItem().toString());
        pstg.setString(2,g);
        pstg.executeUpdate();
        String o1 = CB_GENERO1.getSelectedItem().toString();
        String o2 = CB_GENERO2.getSelectedItem().toString();
        String o3 = CB_GENERO3.getSelectedItem().toString();
        if (o2.equals(o1)){
            System.out.print("son igualiguis");
            }else{
        String sql2 = "Select cod_even from evento where nom_even = '"+ TXT_NOMBRE_E1.getText() +"'";
        Statement st2 = cn.createStatement();
        ResultSet rs2 = st2.executeQuery(sql2);
        rs2.next();
        String ex2 = rs2.getString(1);
        PreparedStatement pstg2 = cn.prepareStatement("INSERT INTO even_gen(cod_even,cod_gen) VALUES (?,?) ");
        pstg2.setString(1, ex2);
        String g2;
        g2 = obtenercod_gen(CB_GENERO2.getSelectedItem().toString());
        pstg2.setString(2,g2);
        pstg2.executeUpdate();
            }
                if (o3.equals(o1) || o3.equals(o1) ){
            System.out.print("son igualiguis");
            }else{
                String sql3 = "Select cod_even from evento where nom_even = '"+ TXT_NOMBRE_E1.getText() +"'";
        Statement st3 = cn.createStatement();
        ResultSet rs3 = st3.executeQuery(sql3);
        rs3.next();
        String ex3 = rs3.getString(1);
        PreparedStatement pstg3 = cn.prepareStatement("INSERT INTO even_gen(cod_even,cod_gen) VALUES (?,?) ");
        pstg3.setString(1, ex3);
        String g3;
        g3 = obtenercod_gen(CB_GENERO3.getSelectedItem().toString());
        pstg3.setString(2,g3);
        pstg3.executeUpdate();
        }
        mostrardatose("");
        Limpiar();
         }  
    } catch (Exception e) {
        System.out.print(e.getMessage());
    } 
        }else {
         JOptionPane.showMessageDialog(null, "Evento duplicado");
        }
        return valor;
    }
    
    
    
    private void tb_eventoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_eventoMouseClicked
              CB_GENERO1.setSelectedIndex(-1);
      CB_GENERO2.setSelectedIndex(-1);
      CB_GENERO3.setSelectedIndex(-1);
        TXT_COD_EVENTO.setText(tb_evento.getValueAt(tb_evento.getSelectedRow(),0).toString()); 
        TXT_NOMBRE_E1.setText(tb_evento.getValueAt(tb_evento.getSelectedRow(),1).toString());
      TXT_DIRECCION_E1.setText(tb_evento.getValueAt(tb_evento.getSelectedRow(),2).toString());
      String b;
      b = obtenernom_cat(tb_evento.getValueAt(tb_evento.getSelectedRow(),3).toString());
      CB_CATEGORIA_E1.setSelectedItem(b);

      String ev = obtenernom_even1(TXT_COD_EVENTO.getText());
      String ev2 = obtenernom_even2(TXT_COD_EVENTO.getText());
      String ev3 = obtenernom_even3(TXT_COD_EVENTO.getText());

      CB_GENERO1.setSelectedItem(obtenernom_gen(ev));
      CB_GENERO2.setSelectedItem(obtenernom_gen(ev2));
      CB_GENERO3.setSelectedItem(obtenernom_gen(ev3));
      TXT_CONTACTO_E1.setText(tb_evento.getValueAt(tb_evento.getSelectedRow(),4).toString());
      TXT_DESCRIPCION_E1.setText(tb_evento.getValueAt(tb_evento.getSelectedRow(),5).toString()); 
      TXT_FECHA_E.setText(tb_evento.getValueAt(tb_evento.getSelectedRow(),6).toString());
      TXT_LATITUD_E.setText(tb_evento.getValueAt(tb_evento.getSelectedRow(),7).toString());
      TXT_LONGITUD_E.setText(tb_evento.getValueAt(tb_evento.getSelectedRow(),8).toString()); 
    // TODO add your handling code here:
    }//GEN-LAST:event_tb_eventoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        if (TXT_NOMBRE_E1.getText().equals("") || TXT_DIRECCION_E1.getText().equals("") || TXT_LATITUD_E.getText().equals("")|| TXT_LONGITUD_E.getText().equals("") || TXT_FECHA_E.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No puede dejar campos en blanco.");
        }else{
        String a;
        a = obtenercod_cat(CB_CATEGORIA_E1.getSelectedItem().toString());
        PreparedStatement pst = cn.prepareStatement("UPDATE evento SET nom_even='"+TXT_NOMBRE_E1.getText()+"',direccion_e='"+TXT_DIRECCION_E1.getText()+"'"
                + ",cod_cat='"+a+"',contacto_e='"+TXT_CONTACTO_E1.getText()+"',descripcion_e='"+TXT_DESCRIPCION_E1.getText()+"'"
                        + ",latitud_e='"+TXT_LATITUD_E.getText()+"',longitud_e='"+TXT_LONGITUD_E.getText()+"' WHERE cod_even='"+TXT_COD_EVENTO.getText()+"'");
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Evento Actualizado");
        mostrardatose("");
        Limpiar();
                        }
    } catch (Exception e) {
        System.out.print(e.getMessage());
    }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int fila = tb_evento.getSelectedRow();
    String cod="";
    cod=tb_evento.getValueAt(fila, 0).toString();
    
    try {

        PreparedStatement pst = cn.prepareStatement("DELETE FROM evento WHERE  cod_even='"+cod+"'");
        pst.executeUpdate();
        PreparedStatement pste = cn.prepareStatement("DELETE FROM even_gen WHERE  cod_even='"+cod+"'");
        pste.executeUpdate();
        JOptionPane.showMessageDialog(null, "Evento Eliminado");
        Limpiar();
        mostrardatose("");

    } catch (Exception e) {
    }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CB_CATEGORIA_E1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CB_CATEGORIA_E1ItemStateChanged
        String aux;
        aux =obtenercod_cat(CB_CATEGORIA_E1.getSelectedItem().toString());
        Obtener_genero(aux);
    }//GEN-LAST:event_CB_CATEGORIA_E1ItemStateChanged

    public void Obtener_genero(String valor){
        DefaultComboBoxModel combobx = new DefaultComboBoxModel();
        DefaultComboBoxModel combobx2 = new DefaultComboBoxModel();
        DefaultComboBoxModel combobx3 = new DefaultComboBoxModel();
        CB_GENERO1.setModel(combobx); 
        CB_GENERO2.setModel(combobx2);
        CB_GENERO3.setModel(combobx3);
    String sql="";
    sql="SELECT * FROM genero where cod_cat ='"+valor+"'";
   
    String nombre;
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                nombre=rs.getString(2);

                CB_GENERO1.addItem(nombre);
                CB_GENERO2.addItem(nombre);
                CB_GENERO3.addItem(nombre);                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Agregar_Evento.class.getName()).log(Level.SEVERE, null, ex);
        }
        CB_GENERO1.setSelectedIndex(-1);
        CB_GENERO2.setSelectedIndex(-1);
        CB_GENERO3.setSelectedIndex(-1); 
    }
    String obtenernom_even1(String valor){

        String []datos = new String [3];
        try {
            String csql = "SELECT cod_gen FROM even_gen WHERE cod_even='"+valor+"'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(csql);
            rs.next();
            datos[0]=rs.getString(1);
            if (datos[0].equals("")) {
                 valor = "";
                }else{
                valor = datos[0];
                }
        }
        catch(Exception e){
            valor = "";              
        }
        return valor;
    }
        String obtenernom_even2(String valor){

        String []datos = new String [3];
        try {
            String csql = "SELECT cod_gen FROM even_gen WHERE cod_even='"+valor+"'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(csql);
            rs.next();
            rs.next();
            datos[0]=rs.getString(1);
                if (datos[0].equals("")) {
                valor = "";
                }else{
                    valor = datos[0];
                }
        }
        catch(Exception e){
            valor = "";             
        }
        return valor;
    }
            String obtenernom_even3(String valor){

        String []datos = new String [3];
        try {
            String csql = "SELECT cod_gen FROM even_gen WHERE cod_even='"+valor+"'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(csql);
            rs.next();
                        rs.next();
                                    rs.next();
                datos[0]=rs.getString(1);
                if (datos[0].equals("")) {
                valor = "";
                }else{
                    valor = datos[0];
                }

        }
        catch(Exception e){
            valor = "";              
        }
        return valor;
    }
     String obtenercod_gen(String valor){
        String dato;
        try {
            String csql = "SELECT cod_gen FROM genero WHERE nom_gen='"+valor+"'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(csql);
            while(rs.next()){
                dato=rs.getString(1);  
                valor = dato;
            } 
        }
        catch(Exception e){
            System.out.println("Falló la carga del combobox \n"+e);              
        }
        return valor;
    }   
    String obtenercod_cat(String valor){
        String dato;
        try {
            String csql = "SELECT cod_cat FROM categoria WHERE nom_cat='"+valor+"'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(csql);
            while(rs.next()){
                dato=rs.getString(1);  
                valor = dato;
            } 
        }
        catch(Exception e){
            System.out.println("Falló la carga del combobox \n"+e);              
        }
        return valor;
    }
    String obtenernom_cat(String valor){
        String dato;
        try {
            String csql = "SELECT nom_cat FROM categoria WHERE cod_cat='"+valor+"'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(csql);
            while(rs.next()){
                dato=rs.getString(1);  
                valor = dato;
            } 
     }
    catch(Exception e){
            System.out.println("Falló la carga del combobox \n"+e);              
        }
        return valor;
    }
        String obtenernom_gen(String valor){
        String dato;
        try {
            String csql = "SELECT nom_gen FROM genero WHERE cod_gen='"+valor+"'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(csql);
            while(rs.next()){
                dato=rs.getString(1);  
                valor = dato;
            } 
     }
    catch(Exception e){
            System.out.println("Falló la carga del combobox \n"+e);              
        }
        return valor;
    }

   
    public void Limpiar(){
        TXT_FECHA_E.setText("");
      TXT_CONTACTO_E1.setText("");
    TXT_DESCRIPCION_E1.setText("");
    TXT_DIRECCION_E1.setText("");
    TXT_LATITUD_E.setText("");
    TXT_LONGITUD_E.setText("");
    TXT_NOMBRE_E1.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Evento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Evento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ACEPTAR;
    private javax.swing.JButton BTN_SALIR;
    private javax.swing.JComboBox<String> CB_CATEGORIA_E1;
    private javax.swing.JComboBox<String> CB_GENERO1;
    private javax.swing.JComboBox<String> CB_GENERO2;
    private javax.swing.JComboBox<String> CB_GENERO3;
    private javax.swing.JLabel TXT_COD_EVENTO;
    private javax.swing.JTextField TXT_CONTACTO_E1;
    private javax.swing.JTextField TXT_DESCRIPCION_E1;
    private javax.swing.JTextField TXT_DIRECCION_E1;
    private javax.swing.JTextField TXT_FECHA_E;
    private javax.swing.JTextField TXT_LATITUD_E;
    private javax.swing.JTextField TXT_LONGITUD_E;
    private javax.swing.JTextField TXT_NOMBRE_E1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_evento;
    // End of variables declaration//GEN-END:variables
}
