/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Categoria;
import Clases.Conectar;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Nacho
 */
public class Agregar_Local extends javax.swing.JFrame {


    Statement st = null;
    ResultSet rs = null;

    Conectar cc= new Conectar();
    Connection cn= cc.conexion();
    /**
     * Creates new form Agregar_Local
     */
    public Agregar_Local() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrardatos("");
    }
 
void mostrardatos(String valor){
    DefaultTableModel modelo= new DefaultTableModel();
    modelo.addColumn("Código");
    modelo.addColumn("Nombre");    
    modelo.addColumn("Dirección");
    modelo.addColumn("Categoría");
    modelo.addColumn("Contacto");
    modelo.addColumn("Descripción");
    modelo.addColumn("Latitud");
    modelo.addColumn("Longitud");    
    tb_local.setModel(modelo);
    String sql="";
    if(valor.equals(""))
    {
        sql="SELECT * FROM local";
    }
    else{
        sql="SELECT * FROM local WHERE cod_local='"+valor+"'";
    }
    
        String []datos = new String [8];
        try {
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                datos[0]=rs.getString(1);
                
                datos[1]=rs.getString(2);
                datos[2]=rs.getString(6);
                String c;
                c = obtenernom_cat(rs.getString(3));
                datos[3]=c;
                datos[4]=rs.getString(4);
                datos[5]=rs.getString(5);
                datos[6]=rs.getString(7);
                datos[7]=rs.getString(8);
                modelo.addRow(datos);
            }
            tb_local.setModel(modelo);
        } catch (SQLException ex) {
            Logger.getLogger(Agregar_Local.class.getName()).log(Level.SEVERE, null, ex);
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXT_COD_LOCAL = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BTN_SALIR = new javax.swing.JButton();
        BTN_ACEPTAR = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TXT_DIRECCION_L = new javax.swing.JTextField();
        TXT_NOMBRE_L = new javax.swing.JTextField();
        CB_CATEGORIA_L = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        TXT_DESCRIPCION_L = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TXT_CONTACTO_L = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TXT_LATITUD_L = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TXT_LONGITUD_L = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_local = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        BTN_Eliminar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        TXT_COD_LOCAL.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(570, 510));
        setMinimumSize(new java.awt.Dimension(570, 510));
        setPreferredSize(new java.awt.Dimension(570, 510));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Detalle de Locales");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(198, 15, 178, 22);

        BTN_SALIR.setText("Atrás");
        BTN_SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_SALIR);
        BTN_SALIR.setBounds(430, 420, 100, 23);

        BTN_ACEPTAR.setText("Agregar");
        BTN_ACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ACEPTARActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_ACEPTAR);
        BTN_ACEPTAR.setBounds(20, 420, 90, 23);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 20, 60, 14);

        jLabel3.setText("Dirección");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 60, 70, 14);

        jLabel4.setText("Categoría");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 90, 70, 14);
        jPanel1.add(TXT_DIRECCION_L);
        TXT_DIRECCION_L.setBounds(80, 50, 434, 30);

        TXT_NOMBRE_L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_NOMBRE_LActionPerformed(evt);
            }
        });
        jPanel1.add(TXT_NOMBRE_L);
        TXT_NOMBRE_L.setBounds(78, 13, 430, 30);

        CB_CATEGORIA_L.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MUSICA", "CINEMATOGRAFICO", "COMIDA", "OTROS" }));
        CB_CATEGORIA_L.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_CATEGORIA_LActionPerformed(evt);
            }
        });
        jPanel1.add(CB_CATEGORIA_L);
        CB_CATEGORIA_L.setBounds(80, 90, 130, 20);

        jLabel5.setText("Descripción");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 170, 70, 30);
        jPanel1.add(TXT_DESCRIPCION_L);
        TXT_DESCRIPCION_L.setBounds(80, 160, 434, 40);

        jLabel6.setText("Contacto");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(10, 120, 70, 14);
        jPanel1.add(TXT_CONTACTO_L);
        TXT_CONTACTO_L.setBounds(80, 120, 434, 30);

        jLabel7.setText("Latitud");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 210, 60, 20);
        jPanel1.add(TXT_LATITUD_L);
        TXT_LATITUD_L.setBounds(80, 210, 174, 30);

        jLabel8.setText("Longitud");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(270, 210, 70, 20);
        jPanel1.add(TXT_LONGITUD_L);
        TXT_LONGITUD_L.setBounds(340, 210, 180, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 38, 530, 250);

        tb_local.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_local.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_localMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_local);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 294, 538, 110);

        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 420, 100, 23);

        BTN_Eliminar.setText("Eliminar");
        BTN_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_Eliminar);
        BTN_Eliminar.setBounds(290, 420, 100, 23);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/Fondo-celeste-copia-1024x1024.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 600, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SALIRActionPerformed
            Inicio v1 = new Inicio();
            dispose();
            v1.setVisible(true);
    }//GEN-LAST:event_BTN_SALIRActionPerformed

    private void TXT_NOMBRE_LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_NOMBRE_LActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_NOMBRE_LActionPerformed

    private void BTN_ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ACEPTARActionPerformed
         String nombre = TXT_NOMBRE_L.getText();  
        String direccion = TXT_DIRECCION_L.getText();
        validar_local(nombre,direccion); 
        mostrardatos("");
        Limpiar();
    }//GEN-LAST:event_BTN_ACEPTARActionPerformed

    private void tb_localMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_localMouseClicked
        TXT_COD_LOCAL.setText(tb_local.getValueAt(tb_local.getSelectedRow(),0).toString()); 
        TXT_NOMBRE_L.setText(tb_local.getValueAt(tb_local.getSelectedRow(),1).toString());
      TXT_DIRECCION_L.setText(tb_local.getValueAt(tb_local.getSelectedRow(),2).toString());
      String b;
      b = obtenernom_cat(tb_local.getValueAt(tb_local.getSelectedRow(),3).toString());
      CB_CATEGORIA_L.setSelectedItem(b);
      TXT_CONTACTO_L.setText(tb_local.getValueAt(tb_local.getSelectedRow(),4).toString());
      TXT_DESCRIPCION_L.setText(tb_local.getValueAt(tb_local.getSelectedRow(),5).toString()); 
      TXT_LATITUD_L.setText(tb_local.getValueAt(tb_local.getSelectedRow(),6).toString());
      TXT_LONGITUD_L.setText(tb_local.getValueAt(tb_local.getSelectedRow(),7).toString()); 
      // TODO add your handling code here:
    }//GEN-LAST:event_tb_localMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    try {
        if (TXT_NOMBRE_L.getText().equals("") || TXT_DIRECCION_L.getText().equals("") || TXT_LATITUD_L.getText().equals("")|| TXT_LONGITUD_L.getText().equals("")){
            JOptionPane.showMessageDialog(null, "No puede dejar campos en blanco.");
        }else{
        String a;
        a = obtenercod_cat(CB_CATEGORIA_L.getSelectedItem().toString());
        PreparedStatement pst = cn.prepareStatement("UPDATE local SET nom_local='"+TXT_NOMBRE_L.getText()+"',direccion_l='"+TXT_DIRECCION_L.getText()+"'"
                + ",cod_cat='"+a+"',contacto_l='"+TXT_CONTACTO_L.getText()+"',descripcion_l='"+TXT_DESCRIPCION_L.getText()+"'"
                        + ",latitud_l='"+TXT_LATITUD_L.getText()+"',longitud_l='"+TXT_LONGITUD_L.getText()+"' WHERE cod_local='"+TXT_COD_LOCAL.getText()+"'");
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Local Actualizado");
        mostrardatos("");
        Limpiar();
                        }
    } catch (Exception e) {
        System.out.print(e.getMessage());
    }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BTN_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EliminarActionPerformed
    int fila = tb_local.getSelectedRow();
    String cod="";
    cod=tb_local.getValueAt(fila, 0).toString();
    
    try {

        PreparedStatement pst = cn.prepareStatement("DELETE FROM local WHERE  cod_local='"+cod+"'");
        pst.executeUpdate();
        PreparedStatement dpst = cn.prepareStatement("DELETE FROM local_prod WHERE  cod_local='"+cod+"'");
        dpst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Local Eliminado");
        Limpiar();
        mostrardatos("");

    } catch (Exception e) {
    }        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_EliminarActionPerformed

    private void CB_CATEGORIA_LActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_CATEGORIA_LActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_CATEGORIA_LActionPerformed

  

    String obtenercod_cat(String valor){
        String dato;
        try {
            String csql = "SELECT cod_cat FROM categoria WHERE nom_cat='"+valor+"'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(csql);
            while(rs.next()){
                dato=rs.getString(1);  
                valor = dato;
            } 
        }
        catch(Exception e){
            System.out.println("Falló la carga del combobox \n"+e);              
        }
        return valor;
    }
    
        String obtenernom_cat(String valor){
        String dato;
        try {
            String csql = "SELECT nom_cat FROM categoria WHERE cod_cat='"+valor+"'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(csql);
            while(rs.next()){
                dato=rs.getString(1);  
                valor = dato;
            } 
        }
        catch(Exception e){
            System.out.println("Falló la carga del combobox \n"+e);              
        }
        return valor;
    }

    String validar_local(String valor , String valor2){
        String vali = "";
        try {
            String csql = "SELECT * FROM local WHERE nom_local='"+valor+"' and direccion_l = '"+valor2+"'";
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(csql);
            while(rs.next()){
                vali=rs.getString(1); 
            } 
        }
        catch(Exception e){
            System.out.println("Falló la carga del combobox \n"+e);              
        }
        if (vali.equals("")){
            try {

                if (TXT_NOMBRE_L.getText().equals("") || TXT_DIRECCION_L.getText().equals("") || TXT_LATITUD_L.getText().equals("")|| TXT_LONGITUD_L.getText().equals("")){
                                            JOptionPane.showMessageDialog(null, "No puede dejar campos en blanco.");
                }else{
      
        PreparedStatement pst = cn.prepareStatement("INSERT INTO local(nom_local,cod_cat,contacto_l,descripcion_l,direccion_l,latitud_l,longitud_l) VALUES (?,?,?,?,?,?,?)");
        pst.setString(1, TXT_NOMBRE_L.getText().toUpperCase());
        pst.setString(5, TXT_DIRECCION_L.getText());
        String a;
        a = obtenercod_cat(CB_CATEGORIA_L.getSelectedItem().toString());
        pst.setString(2,a);
        pst.setString(3, TXT_CONTACTO_L.getText());
        pst.setString(4, TXT_DESCRIPCION_L.getText());
        pst.setString(6,TXT_LATITUD_L.getText());
        pst.setString(7, TXT_LONGITUD_L.getText());
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Local Agregado");
        mostrardatos("");
        Limpiar();
         }
    } catch (Exception e) {
        System.out.print(e.getMessage());
    }
        }else {
         JOptionPane.showMessageDialog(null, "Local duplicado");
        }
        return valor;
    }
    public void Limpiar(){
    TXT_CONTACTO_L.setText("");
    TXT_DESCRIPCION_L.setText("");
    TXT_DIRECCION_L.setText("");
    TXT_LATITUD_L.setText("");
    TXT_LONGITUD_L.setText("");
    TXT_NOMBRE_L.setText("");
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar_Local.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar_Local.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar_Local.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar_Local.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar_Local().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_ACEPTAR;
    private javax.swing.JButton BTN_Eliminar;
    private javax.swing.JButton BTN_SALIR;
    private javax.swing.JComboBox<String> CB_CATEGORIA_L;
    private javax.swing.JTextField TXT_COD_LOCAL;
    private javax.swing.JTextField TXT_CONTACTO_L;
    private javax.swing.JTextField TXT_DESCRIPCION_L;
    private javax.swing.JTextField TXT_DIRECCION_L;
    private javax.swing.JTextField TXT_LATITUD_L;
    private javax.swing.JTextField TXT_LONGITUD_L;
    private javax.swing.JTextField TXT_NOMBRE_L;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_local;
    // End of variables declaration//GEN-END:variables
}
