/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

/**
 *
 * @author Nacho
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BTN_LOCAL = new javax.swing.JButton();
        BTN_EVENTO = new javax.swing.JButton();
        BTN_PRODUCTO = new javax.swing.JButton();
        BTN_SALIR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 330));
        setMinimumSize(new java.awt.Dimension(400, 330));
        setPreferredSize(new java.awt.Dimension(400, 330));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Mantenedores de la Aplicación");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(93, 39, 181, 17);

        BTN_LOCAL.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTN_LOCAL.setText("Local");
        BTN_LOCAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_LOCALActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_LOCAL);
        BTN_LOCAL.setBounds(141, 82, 86, 32);

        BTN_EVENTO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTN_EVENTO.setText("Evento");
        BTN_EVENTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_EVENTOActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_EVENTO);
        BTN_EVENTO.setBounds(141, 143, 86, 33);

        BTN_PRODUCTO.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BTN_PRODUCTO.setText("Producto");
        BTN_PRODUCTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_PRODUCTOActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_PRODUCTO);
        BTN_PRODUCTO.setBounds(141, 202, 86, 31);

        BTN_SALIR.setText("Salir");
        BTN_SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_SALIRActionPerformed(evt);
            }
        });
        getContentPane().add(BTN_SALIR);
        BTN_SALIR.setBounds(308, 244, 53, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Ventanas/Fondo-celeste-copia-1024x1024.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_LOCALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_LOCALActionPerformed
            Agregar_Local v1_1 = new Agregar_Local();
            dispose();
            v1_1.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_BTN_LOCALActionPerformed

    private void BTN_SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_SALIRActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BTN_SALIRActionPerformed

    private void BTN_EVENTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_EVENTOActionPerformed
            Agregar_Evento v2 = new Agregar_Evento();
            dispose();
            v2.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_BTN_EVENTOActionPerformed

    private void BTN_PRODUCTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_PRODUCTOActionPerformed
          MENU_Producto v3 = new MENU_Producto();
          dispose();
          v3.setVisible(true);          // TODO add your handling code here:
    }//GEN-LAST:event_BTN_PRODUCTOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_EVENTO;
    private javax.swing.JButton BTN_LOCAL;
    private javax.swing.JButton BTN_PRODUCTO;
    private javax.swing.JButton BTN_SALIR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
